/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FantasyLand: typeof import('./src/components/FantasyLand.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PeopleWithAvatar: typeof import('./src/components/widgets/PeopleWithAvatar.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signature: typeof import('./src/components/Signature.vue')['default']
    TargetLink: typeof import('./src/components/widgets/TargetLink.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
